/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksScanAllEmailsRouteImport } from './routes/hooks/scan-all-emails'
import { Route as AuthenticatedVatRouteImport } from './routes/_authenticated/vat'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiNylasCallbackRouteImport } from './routes/api/nylas/callback'
import { Route as AuthenticatedPortalUploadRouteImport } from './routes/_authenticated/portal.upload'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedPortalConnectionsRouteImport } from './routes/_authenticated/portal.connections'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksScanAllEmailsRoute = HooksScanAllEmailsRouteImport.update({
  id: '/hooks/scan-all-emails',
  path: '/hooks/scan-all-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVatRoute = AuthenticatedVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiNylasCallbackRoute = ApiNylasCallbackRouteImport.update({
  id: '/api/nylas/callback',
  path: '/api/nylas/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalUploadRoute =
  AuthenticatedPortalUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalConnectionsRoute =
  AuthenticatedPortalConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/vat': typeof AuthenticatedVatRoute
  '/hooks/scan-all-emails': typeof HooksScanAllEmailsRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/portal/connections': typeof AuthenticatedPortalConnectionsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/upload': typeof AuthenticatedPortalUploadRoute
  '/api/nylas/callback': typeof ApiNylasCallbackRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/vat': typeof AuthenticatedVatRoute
  '/hooks/scan-all-emails': typeof HooksScanAllEmailsRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/portal/connections': typeof AuthenticatedPortalConnectionsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/upload': typeof AuthenticatedPortalUploadRoute
  '/api/nylas/callback': typeof ApiNylasCallbackRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/vat': typeof AuthenticatedVatRoute
  '/hooks/scan-all-emails': typeof HooksScanAllEmailsRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/portal/connections': typeof AuthenticatedPortalConnectionsRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/upload': typeof AuthenticatedPortalUploadRoute
  '/api/nylas/callback': typeof ApiNylasCallbackRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/portal'
    | '/vat'
    | '/hooks/scan-all-emails'
    | '/clients/$clientId'
    | '/clients/new'
    | '/portal/connections'
    | '/portal/documents'
    | '/portal/upload'
    | '/api/nylas/callback'
    | '/clients/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/documents'
    | '/vat'
    | '/hooks/scan-all-emails'
    | '/clients/$clientId'
    | '/clients/new'
    | '/portal/connections'
    | '/portal/documents'
    | '/portal/upload'
    | '/api/nylas/callback'
    | '/clients'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/portal'
    | '/_authenticated/vat'
    | '/hooks/scan-all-emails'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/portal/connections'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/upload'
    | '/api/nylas/callback'
    | '/_authenticated/clients/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  HooksScanAllEmailsRoute: typeof HooksScanAllEmailsRoute
  ApiNylasCallbackRoute: typeof ApiNylasCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/scan-all-emails': {
      id: '/hooks/scan-all-emails'
      path: '/hooks/scan-all-emails'
      fullPath: '/hooks/scan-all-emails'
      preLoaderRoute: typeof HooksScanAllEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vat': {
      id: '/_authenticated/vat'
      path: '/vat'
      fullPath: '/vat'
      preLoaderRoute: typeof AuthenticatedVatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/nylas/callback': {
      id: '/api/nylas/callback'
      path: '/api/nylas/callback'
      fullPath: '/api/nylas/callback'
      preLoaderRoute: typeof ApiNylasCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/upload': {
      id: '/_authenticated/portal/upload'
      path: '/upload'
      fullPath: '/portal/upload'
      preLoaderRoute: typeof AuthenticatedPortalUploadRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/connections': {
      id: '/_authenticated/portal/connections'
      path: '/connections'
      fullPath: '/portal/connections'
      preLoaderRoute: typeof AuthenticatedPortalConnectionsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalConnectionsRoute: typeof AuthenticatedPortalConnectionsRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalUploadRoute: typeof AuthenticatedPortalUploadRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalConnectionsRoute: AuthenticatedPortalConnectionsRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalUploadRoute: AuthenticatedPortalUploadRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedVatRoute: typeof AuthenticatedVatRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedVatRoute: AuthenticatedVatRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  HooksScanAllEmailsRoute: HooksScanAllEmailsRoute,
  ApiNylasCallbackRoute: ApiNylasCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
